### ISSUE TITLE
Allow some threads to 'leak'

### ISSUE THREAD

**Issue by jayvdb** [nirs/pytest-threadleak#7]
https://pypi.org/project/pymongo/ creates a lot of threads behind the screens.

It has an `atexit` handler which cleans up most of them at https://github.com/mongodb/mongo-python-driver/blob/5578999/pymongo/monitor.py#L440

It would be nice to be able to exclude these threads from leak detection, based on the thread name, or something similar, so leak detection can focus on the other potential sources of leaks.

**Comment by nirs** [comment]
Creating threads lazily and terminating them in atexit sounds little bit messy,
but I can see why it may be useful to create threads lazily.

Exluding threads by name sounds good. It can work like this:

Example config:

    [threadleak]
    exclude = threadpool/.+

Example argument:

    @pytest.mark.threadleak(exclude="threadpool/.+")
    def test_exclude_threads():

With this configuration, thread named "threadpool/1" will be ignored
when comparing the threads before the test to the threads after the test.

@jayvdb do you want to send a PR?

**Comment by jayvdb** [comment]
I had already created a branch yesterday, so I have submitted that as a PR.

I dont mind changing the config name to what you suggest here, and would like to create some tests for it also.

**Comment by jayvdb** [comment]
fwiw, in my case I dont want to be using a "mark" approach on each test, because it is almost every test in a large suite.

**Comment by nirs** [comment]
> fwiw, in my case I dont want to be using a "mark" approach on each test, because it is almost every test in a large suite.

Sure, excluding single test will not be useful for this case. But markers work also for class
and module context. Ideally we will have an option that can be used in all context: global, module, class, function.

See the existing tests for examples, I think it should be easy to support all cases.
